# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# windowrules
windowrule = match:class kitty, float on, size 800 400, center on
windowrule = match:class Alacritty, float on, size 800 400, center on
windowrule = match:class clipse-gui, match:title Clipse GUI, float on, size 600 800, center on
windowrule = match:title Picture-in-Picture, float on, size 450 250, pin on, move 1450 815
windowrule = match:title satty, float on, size 800 600, center on
layerrule = match:namespace wallpaper-picker, blur off
layerrule = ignore_alpha 0.1, match:namespace wallpaper-picker
layerrule = match:namespace wallpaper-picker, animation popup 70%
layerrule = match:namespace rofi, blur off
layerrule = ignore_alpha 0.1, match:namespace rofi
layerrule = match:class dolphin, blur on
layerrule = match:namespace waybar, blur disable
layerrule = match:namespace rofi, animation popin 80%
layerrule = match:namespace swaync-control-center, blur on
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = match:namespace swaync-notification-window, blur on
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window
layerrule = match:namespace quickshell, animation fade
layerrule = match:namespace logout_dialog, animation fade
layerrule = match:namespace waybar, animation slide top
layerrule = match:namespace gtk-layer-shell, blur disable
layerrule = match:namespace gtk4-layer-shell, blur disable
workspace = special:Spotify, persistent:false
layerrule = match:namespace bongocat-overlay, blur disable
windowrule = match:class spotify, workspace special:Spotify
layerrule = match:namespace selection, blur disable
layerrule = match:namespace selection, animation fade


#smart-gaps
workspace = w[tv1], gapsout:10, gapsin:5
workspace = f[1], gapsout:10, gapsin:5
windowrule = border_size 1, match:float 0, match:workspace w[tv1]
windowrule = rounding 5, match:float 0, match:workspace w[tv1]
windowrule = border_size 1, match:float 0, match:workspace f[1]
windowrule = rounding 5, match:float 0, match:workspace f[1]
