exec-once = swww-daemon
exec-once = waybar
exec-once = clipse -listen
exec-once = hypridle
exec-once = swaync 
exec-once = /home/luisp/.config/hypr/scripts/monitor_wallpaper.sh
exec-once = systemctl --user start hyprpolkitagent
exec-once = kbuildsycoca6
exec-once = eww daemon
exec-once = eww open activate-linux
exec-once = playerctld daemon
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = bongocat -t
