# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# windowrules
windowrule = match:class kitty, float on, size 800 400, center on
windowrule = match:class Alacritty, float on, size 800 400, center on
windowrule = match:class clipse-gui, match:title Clipse GUI, float on, size 600 800, center on
windowrule = match:title Picture-in-Picture, float on, size 450 250, pin on, move 1450 815
layerrule = match:namespace rofi, blur on
layerrule = match:class dolphin, blur on
layerrule = match:namespace waybar, blur disable
layerrule = match:namespace selection, blur disable
layerrule = match:namespace swaync-control-center, blur disable
layerrule = match:namespace swaync-notification-window, blur disable
workspace = special:Spotify, persistent:false
windowrule = match:class Spotify, workspace special:Spotify

